version: 2.1

workflows:
  workflow:
    jobs:
      - env-scope-test

jobs:
  env-scope-test:
    docker:
      - image: cimg/base:2024.01-22.04
        environment:
          AWS_ACCESS_KEY_ID: "key"
    steps:
      #- run:
       #   name: Verify Initial Env Values
        #  command: echo ${AWS_ACCESS_KEY_ID}
      #- run:
      #    name: Remove Env
      #    command: AWS_ACCESS_KEY_ID=KEY2 && echo ${AWS_ACCESS_KEY_ID}
      #- run:
      #    name: Verify Final Env Values
#          command: echo ${AWS_ACCESS_KEY_ID}
      - run:
          name: Create new variable
          command: NEWVARIABLE=HELLO
      - run:
          name: Verify New Variable
          command: echo ${NEWVARIABLE}
      - run:
          name: Change New Variable
          command: NEWVARIABLE=WORLD
      - run:
          name: Verify New Variable AGAIN
          command: echo ${NEWVARIABLE}
