version: 2.1
nodejs: &nodejs
  working_directory: ~/project
  docker:
    - image: circleci/node:12
  environment:
    REACT_APP_API_URL: $BACKEND
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  install:
    <<: *nodejs
    steps:
      - checkout
      - run:
          name: Charge environment variables
          command: echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env
      - run:
          name: Install nodejs packages
          command: npm ci
      - persist_to_workspace:
          root: ~/project
          paths: .
  test:
    <<: *nodejs
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run unit tests
          command: npm t
  build:
    <<: *nodejs
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build deployable files
          command: CI=false npm run build && ls
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy built files to S3
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          command: aws s3 cp build/* s3://pizzas-front --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive
workflows:
  version: 2
  deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build